services:
  - docker:dind

build:
  image: docker:latest
  before_script:
    - apk update
    - apk add docker-compose
  script:
    - docker-compose --project-directory . -f .local/share/rage/docker-compose.yml build
