image: docker:latest

before_script:
    - docker create -v /usr/portage --name portage gentoo/portage
  
test:
  stage: test
  script:
    - docker run --volumes-from portage --name gentoo -it -v $(pwd):/home/repoman/ lramage94/repoman /bin/sh -c "ARCH=x86_64 ACCEPT_KEYWORDS='' repoman -dxi full"