image: alpine:3.9

before_script:
    - apk update && apk add bash git python py2-lxml py2-pip rsync wget xz
    - pip install pyyaml
    - git clone https://anongit.gentoo.org/git/proj/portage.git
    - cd portage && ./setup.py install
    - cd repoman && ./setup.py install
    - cd ../.. && rm -rf portage
    - adduser -S portage && addgroup portage
    - git clone https://gitlab.com/oxr463/gentoo.git /usr/portage
    - mkdir -p /var/cache/distfiles

test:
  stage: test
  script:
    - PORTDIR='/usr/portage' ARCH=x86_64 ACCEPT_KEYWORDS='' repoman -dxi full
